# WARNING: All command substitutions in this file are passed directly to the shell.
#          Exercise caution when using variables or user-provided input in your build commands
#          to prevent potential security vulnerabilities.

# A profile to be used if not specified while running the build script
PreferredProfile: 
    DefaultPlatform: "gcc"
    Windows: "msvc"

# List of compiler/linker profiles that instruct how to compile/link
# See "./Default/AnnotatedG++.yaml" for the documentation of each field in a profile entry
# Profiles: []

# (Optional) Same as how parameters in build info. See build info template for more details (`runcpp2 template`)
# Parameters: ...


# (Optional) Same as how variables in build info. See build info template for more details (`runcpp2 template`)
# Variables: ...

# (Optional) Importing other yaml files. Can either be a single path or a list of paths. 
#            See build info template for more details (`runcpp2 template`)
Import: "./Default/DefaultProfiles.yaml"
