Templates:
    FilesTypes: &CommonFilesTypes
        ObjectLinkFile:
            Prefix:
                All: ""
            Extension:
                Windows: ".obj"
                Unix: ".o"
        
        # The file properties for the files to be **linked** as shared libraries for each platform
        SharedLinkFile:
            Prefix:
                Windows: ""
                Linux: "lib"
                MacOS: ""
            Extension:
                Windows: ".lib"
                Linux: ".so"
                MacOS: ".dylib"
        
        # The file properties for the files to be **copied** as shared libraries for each platform
        SharedLibraryFile:
            Prefix:
                Windows: ""
                Linux: "lib"
                MacOS: ""
            Extension:
                Windows: ".dll"
                Linux: ".so"
                MacOS: ".dylib"
        
        # The file properties for the files to be linked as static libraries for each platform
        StaticLinkFile:
            Prefix:
                Unix: "lib"
                Windows: ""
            Extension:
                Windows: ".lib"
                Unix: ".a"

        # (Optional) The file properties for debug symbols to be copied alongside the binary 
        #   for each platform
        DebugSymbolFile:
            Prefix:
                Windows: ""
                Unix: ""
            Extension:
                Windows: ""
                Unix: ""

# A profile to be used if not specified while running the build script
PreferredProfile: "g++"

# List of compiler/linker profiles that instruct how to compile/link
Profiles:
    # Name (case sensitive) of the profile that can be queried from a script
-   Name: "g++"
    
    # (Optional) Name aliases (case sensitive) of the current profile
    NameAliases: ["mingw"]
    
    # The file extensions associated with the profile
    FileExtensions: [cpp, cc, cxx]
    
    # The languages supported by the profile
    Languages: ["c++"]
    
    # The following fields set the prefixes and extensions for each type of the files
    # If the name of an object files are libtest.so and libtest2.so,
    #   the prefixes and extensions are "lib" and ".so"
    
    # Each of the platform dependent settings can be listed under
    # - All
    # - Windows
    # - Linux
    # - MacOS
    # - Unix
    
    # (Optional) The commands to run in **shell**  before calling the compiler/linker for each platform.
    #            This is run inside the .runcpp2 directory where the build happens.
    # SetupSteps: 
    #     All: []
    
    # The file properties for the object files for each platform.
    FilesTypes: *CommonFilesTypes
    
    # Specify the compiler settings
    Compiler:
        # (Optional) The command to run together before running each compile command
        #   in **shell** for each platform
        # PreRun: 
        #     All: ""
        
        # Shell command to use for checking if the executable exists or not
        CheckExistence: 
            All: "g++ -v"
        
        CompileTypes:
            Executable:
                All:
                    Flags: "-std=c++17 -Wall -Werror"
                    Executable: "g++"
            Static:
                All:
                    Flags: "-std=c++17 -Wall -Werror"
                    Executable: "g++"
            Shared:
                All:
                    Flags: "-std=c++17 -Wall -Werror -fpic"
                    Executable: "g++"
        RunParts:
            All:
            -   Type: Once
                CommandPart: "{Executable} -c {CompileFlags}"
            -   Type: Repeats
                CommandPart: " -I{IncludeDirectoryPath}"
            -   Type: Once
                CommandPart: " {InputFilePath} -o {OutputFilePath}"

    # Specify the linker settings
    Linker:
        # (Optional) The command to run together before running each link command 
        #   in **shell** for each platform
        # PreRun: 
        #     All: ""
        
        # Shell command to use for checking if the executable exists or not
        CheckExistence:
            All: "g++ -v"
        
        LinkTypes:
            Executable:
                Unix:
                    Flags: "-Wl,-rpath,\\$ORIGIN"
                    Executable: "g++"
                Windows:
                    Flags: "-Wl,-rpath,$ORIGIN"
                    Executable: "g++"
            Static:
                All:
                    Flags: ""
                    Executable: "g++"
            Shared:
                Unix:
                    Flags: "-shared -Wl,-rpath,\\$ORIGIN"
                    Executable: "g++"
                Windows:
                    Flags: "-shared -Wl,-rpath,$ORIGIN"
                    Executable: "g++"
        RunParts:
            All:
            -   Type: Once
                CommandPart: "{Executable} {CompileFlags} -o {OutputFilePath}"
            -   Type: Repeats
                CommandPart: " {LinkFilePath}"
        

# https://learn.microsoft.com/en-us/cpp/overview/compiler-versions?view=msvc-170
# -   &MSVC_2022
#     Name: "vs2022_v17+"
#     NameAliases: ["msvc1930+", "msvc"]
#     FileExtensions: [cpp, cc, cxx]
#     Languages: ["c++"]
#     
#     ObjectLinkFile:
#         Prefix:
#             Windows: ""
#         Extension:
#             Windows: ".obj"
#     
#     SharedLinkFile:
#         Prefix:
#             Windows: ""
#         Extension:
#             Windows: ".lib"
#     
#     SharedLibraryFile:
#         Prefix:
#             Windows: ""
#         Extension:
#             Windows: ".dll"
#     
#     StaticLinkFile:
#         Prefix:
#             Windows: ""
#         Extension:
#             Windows: ".lib"
#     
#     DebugSymbolFile:
#         Prefix:
#             Windows: ""
#         Extension:
#             Windows: ".pdb"
#     
#     Compiler:
#         EnvironmentSetup: 
#             Windows: "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x64"
#     
#         Executable: "CL.exe"
#         
#         CheckExistence: "where.exe CL.exe"
# 
#         DefaultCompileFlags: 
#             Windows: "/utf-8 /MD /EHa /TP"
#         
#         ExecutableCompileFlags: 
#             Windows: ""
#         
#         StaticLibCompileFlags: 
#             Windows: ""
#         
#         SharedLibCompileFlags: 
#             Windows: ""
#         
#         # Should be: CL.exe /c {CompileFlags} /I{IncludeDirectoryPath} /Fo"{ObjectFilePath}" {InputFilePath}
#         CompileArgs: 
#             CompilePart: "/c {CompileFlags}"
#             IncludePart: "/I{IncludeDirectoryPath}"
#             InputPart: "{InputFilePath}"
#             OutputPart: "/Fo\"{ObjectFilePath}\""
#     
#     Linker:
#         EnvironmentSetup: 
#             Windows: "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x64"
#     
#         Executable: "link.exe"
#         
#         CheckExistence: "where.exe link.exe"
#         
#         DefaultLinkFlags: 
#             Windows: ""
#         
#         ExecutableLinkFlags: 
#             Windows: ""
#         
#         StaticLibLinkFlags: 
#             Windows: ""
#         
#         SharedLibLinkFlags: 
#             Windows: ""
#         
#         LinkArgs:
#             OutputPart: "{LinkFlags} -o {OutputFilePath}"
#             LinkPart: "{LinkFilePath}"
