# WARNING: All command substitutions in this file are passed directly to the shell.
#          Exercise caution when using variables or user-provided input in your build commands
#          to prevent potential security vulnerabilities.

# A profile to be used if not specified while running the build script
PreferredProfile: 
    DefaultPlatform: "g++"
    Windows: "msvc"

# List of compiler/linker profiles that instruct how to compile/link
# See "./Default/g++.yaml" for the documentation of each field in a profile entry
Profiles:
-   Import: "./Default/g++.yaml"
-   Import: "./Default/vs2022_v17+.yaml"
