site_name: runcpp2
site_url: 'https://neko-box-coder.github.io/runcpp2/'

theme:
    name: material
    custom_dir: overrides
    logo: Runcpp2Logo.png
    favicon: favicon.png
    palette:
    -   scheme: slate
        primary: black
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
    -   scheme: default
        primary: black
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    features:
    -   toc.follow
    -   toc.integrate
    -   content.code.copy
    -   content.code.select
    -   navigation.sections
    -   navigation.expand
    -   navigation.tabs
    -   navigation.tabs.sticky

nav:
    -   index.md
    # -   guides.md
    -   Guides:
        -   guides/basic_concepts.md
        -   guides/building_project_sources.md
        -   guides/external_dependencies.md
        -   guides/scriptable_pipeline.md
    -   program_manual.md
    -   build_settings.md
    -   user_config.md
    -   TODO.md

extra_css: [extra.css]
markdown_extensions:
-   admonition
# -   attr_list
# -   material.extensions.preview:
#         targets:
#             include:
#                 -   "build_settings.md"
-   pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
-   pymdownx.inlinehilite
-   pymdownx.snippets
-   pymdownx.details
-   pymdownx.superfences
-   toc:
      toc_depth: 6

extra:
    version:
        provider: mike
